name: Build

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8530928916aaef40f59e6f221989ccb31f5759e7
      - uses: actions/setup-node@2a017f350dbf6c4b6bb4508cc83809719115162e
        with:
          node-version: 18.x
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run format-check
      - run: npm run lint
      - run: npm run compile
      - run: xvfb-run -a npm run test