name: Build

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install Node.js
        uses: actions/setup-node@main
        with:
          node-version: 20.x
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run format-check
        if : runner.os != 'Windows'
      - run: npm run lint
      - run: npm run compile
      - run: xvfb-run -a npm run test
        if: runner.os == 'Linux'
      - run: npm run test
        if: runner.os != 'Linux'